version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: productSchool
      MYSQL_DATABASE: productSchool
      MYSQL_USER: productSchool
      MYSQL_PASSWORD: productSchool

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: productSchool
    working_dir: /var/www/html
    volumes:
      - /Users/Marcos/Documents/wordpressGrunt/wp-content:/var/www/html/wp-content
      - /Users/Marcos/Documents/wordpressGrunt/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
    db_data: